# Generated by Django 5.1.6 on 2025-03-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('instagram', models.CharField(max_length=256, null=True)),
                ('x', models.CharField(max_length=256, null=True)),
                ('github', models.CharField(max_length=256, null=True)),
                ('image', models.ImageField(upload_to='profile_images/')),
            ],
        ),
    ]
