# Generated by Django 5.1.6 on 2025-03-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
