# Generated by Django 5.1.6 on 2025-03-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_admin', '0002_profile_subtitle_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bgimage',
            field=models.ImageField(null=True, upload_to='profile_bgimages/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
    ]
